#!/usr/bin/env bash
# Generate SeaweedFS security.toml + sse.env (K9).
#
# Produces the two files that enable SSE-S3 and silence the missing filer
# signing key:
#
#   data/seaweedfs/conf/security.toml   [s3.sse] kek + [jwt.filer_signing] key
#   data/seaweedfs/conf/sse.env         WEED_S3_SSE_KEK_PASSPHRASE
#
# Both are gitignored and mode 600. Neither is passed through compose
# `environment:`; the spec forbids committed secrets in a compose file
# (avanyam_intro.txt 14.2).
#
# Run once on a new host, before `docker compose up -d`:
#   ./scripts/gen-seaweedfs-security.sh
#
# DANGER: regenerating the KEK makes every existing object unreadable. The KEK
# wraps each object's data key, so a new KEK cannot decrypt data written under
# the old one. There is deliberately no --force flag to make that mistake easy.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF_DIR="$ROOT/data/seaweedfs/conf"
SEC="$CONF_DIR/security.toml"
ENVF="$CONF_DIR/sse.env"

for f in "$SEC" "$ENVF"; do
    if [ -e "$f" ]; then
        echo "refusing to overwrite $f" >&2
        echo "Regenerating the KEK makes every existing SSE-S3 object permanently" >&2
        echo "unreadable, so this script will not do it silently. If you are sure," >&2
        echo "remove it by hand:  sudo rm $f" >&2
        exit 1
    fi
done

mkdir -p "$CONF_DIR"
umask 077

python3 - "$SEC" "$ENVF" <<'PY'
import binascii, os, secrets, sys

sec_path, env_path = sys.argv[1], sys.argv[2]

# Schema taken from the binary's own generator, not from memory:
#   weed scaffold -config=security
# [s3.sse] kek is documented there as a "hex-encoded 256-bit key" with
# "openssl rand -hex 32" as the suggested way to make one.
kek = binascii.hexlify(secrets.token_bytes(32)).decode()
signing = binascii.hexlify(secrets.token_bytes(32)).decode()
# The passphrase wraps the KEK before it is stored on the filer. Without it the
# gateway logs: "the KEK will be stored on the filer in plaintext".
passphrase = secrets.token_urlsafe(48)

with open(sec_path, "w") as fh:
    fh.write(f"""# avanyam_aqua - SeaweedFS security configuration.
#
# GENERATED by scripts/gen-seaweedfs-security.sh - do not edit by hand and do
# not commit. Regenerating the KEK makes existing SSE-S3 objects unreadable.
#
# Schema from: weed scaffold -config=security

[s3.sse]
# Enables SSE-S3. Without it the gateway logs "SSE-S3 encryption is disabled"
# and stores every object in plaintext on the filer volumes.
kek = "{kek}"

[jwt.filer_signing]
# Silences: "Failed to load IAM configuration: no signing key found for STS
# service".
key = "{signing}"
expires_after_seconds = 10
""")

with open(env_path, "w") as fh:
    fh.write(f"WEED_S3_SSE_KEK_PASSPHRASE={passphrase}\n")

os.chmod(sec_path, 0o600)
os.chmod(env_path, 0o600)

print(f"wrote {sec_path}")
print(f"wrote {env_path}")
print()
print("No key material was printed. Both files are mode 600 and gitignored.")
print("next: sudo docker compose up -d && sudo docker logs avanyam-s3 | grep -i sse")
print("  expect: SSE-S3 KeyManager: Loaded KEK from s3.sse.kek config")
PY
