# Generated by Django 5.2.17 on 2026-10-04 10:38

import apps.accounts.domain.enums
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalUndoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='signuprequest',
            name='uniq_signup_email',
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('suspended', 'suspended'), ('redirected', 'redirected')], db_index=True, default=apps.accounts.domain.enums.ApprovalStatus['PENDING'], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('suspended', 'suspended'), ('redirected', 'redirected')], db_index=True, default=apps.accounts.domain.enums.ApprovalStatus['PENDING'], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='signuprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', apps.accounts.domain.enums.ApprovalStatus['REDIRECTED']), _negated=True), fields=('email',), name='uniq_signup_email_open'),
        ),
        migrations.AddField(
            model_name='approvalundotoken',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_tokens', to='accounts.signuprequest'),
        ),
        migrations.AddField(
            model_name='approvalundotoken',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_undo_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalundotoken',
            index=models.Index(fields=['request', 'expires_at'], name='accounts_ap_request_873652_idx'),
        ),
    ]
