# Generated by Django 5.2.17 on 2026-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_approvalundotoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalundotoken',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
