# Generated by Django 5.2.17 on 2026-10-04 21:19
#
# Three product decisions land here.
#
# 1. `SignupRequest.requested_role` replaces trainer selection as the thing that
#    routes an application. Approval became an Admin-only act, so an applicant no
#    longer nominates anyone.
#
# 2. `User.must_change_password` is dropped. Nobody is issued a placeholder
#    password any more: trainees and trainers set their own at signup, and a
#    Trainer creating an account sets one with them, so the forced-change gate had
#    nothing left to gate.
#
# 3. `SignupRequest.created_by` records who filled the form in, for accounts a
#    Trainer or Admin created on somebody else's behalf. This used to exist only
#    as a log field, so it was lost whenever logs rotated.
#
# `selected_trainer` on BOTH `User` and `SignupRequest` is deliberately left in
# place. It no longer decides anything, but dropping the columns would discard the
# record of who was originally nominated and make the change irreversible in
# production. It is marked deprecated in `models.py` and nothing writes it.
#
# Roll safety: `requested_role` and `created_by` are both added with a default,
# so old and new code both run against this schema. Dropping
# `must_change_password` is the one backward-incompatible step -- it is a pre-pilot
# boolean with no data worth preserving, so it is removed outright rather than
# through an expand/contract dance.

import apps.accounts.domain.enums
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_approvalundotoken_emailed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='requested_role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('trainer', 'Trainer')], db_index=True, default=apps.accounts.domain.enums.RequestedRole['TRAINEE'], help_text='Role the applicant asked for. Admin cannot be requested.', max_length=16),
        ),
    ]
