#!/usr/bin/env bash
#
# Rebuild the `avanyam` schema from scratch and re-apply every migration.
#
# WHEN THIS IS CORRECT: during initial bring-up, before the database holds any
# data that is not reproducible from code. Changing AUTH_USER_MODEL after
# migrations have already been recorded is the usual trigger -- Django marks
# 0001_initial as applied, so regenerating the file with a new field silently
# does nothing and the column is missing at runtime.
#
# WHEN THIS IS DESTRUCTIVE: any time real data exists. It issues
# `DROP SCHEMA public CASCADE`. The guard below refuses if any table holds rows
# that this script cannot recreate, so it fails loudly instead of eating data.
#
# Usage:  ./scripts/rebuild-db.sh            # confirm-then-rebuild
#         ./scripts/rebuild-db.sh --force    # skip the row-count guard
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
PY="./avanyam_terra/.avanyam_terra_venv/bin/python"
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

echo "==> Checking for data that is NOT reproducible from source"
NON_RECREATABLE="$("$PY" - <<'PY'
import os, sys
sys.path.insert(0, "src")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
import django; django.setup()
from django.db import connections

# Tables whose rows are regenerated by Django's post_migrate signal, are
# recreated by `manage.py seed_people`, or are transient by nature.
#
# django_session / axes_* are session and lockout bookkeeping. They are
# regenerated on the next request, so wiping them costs nothing.
SAFE = {
    "django_migrations",
    "django_content_type",
    "auth_permission",
    "auth_group",
    "accounts_user",
    "accounts_role",
    "accounts_roleassignment",
    "accounts_signuprequest",
    "django_session",
    "axes_accesslog",
    "axes_accessattempt",
    "axes_accessattemptexpiration",
    "axes_accessfailurelog",
}
bad = []
with connections["migrate"].cursor() as c:
    c.execute("""SELECT table_name FROM information_schema.tables
                 WHERE table_schema='public' AND table_type='BASE TABLE'""")
    for (table,) in c.fetchall():
        if table in SAFE:
            continue
        c.execute(f'SELECT count(*) FROM "{table}"')
        n = c.fetchone()[0]
        if n:
            bad.append(f"{table}={n}")
print(" ".join(bad))
PY
)"

if [[ -n "$NON_RECREATABLE" ]]; then
  if [[ $FORCE -eq 0 ]]; then
    echo "REFUSING: these tables hold rows that are not recreated by this script:" >&2
    echo "  $NON_RECREATABLE" >&2
    echo >&2
    echo "Re-run with --force ONLY if you are certain the data is disposable." >&2
    exit 1
  fi
  echo "WARNING: --force given; discarding rows in: $NON_RECREATABLE"
fi

echo "==> Dropping and recreating schema public"
"$PY" - <<'PY'
import os, sys
sys.path.insert(0, "src")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
import django; django.setup()
from django.db import connections

with connections["migrate"].cursor() as c:
    c.execute("SELECT current_database(), current_user")
    db, usr = c.fetchone()
    print(f"    database={db} as {usr}")

with connections["migrate"].cursor() as c:
    c.execute("DROP SCHEMA public CASCADE")
    c.execute("CREATE SCHEMA public")
    c.execute("ALTER SCHEMA public OWNER TO avanyam_migrate")
    c.execute("GRANT USAGE, CREATE ON SCHEMA public TO avanyam_migrate")
    c.execute("GRANT USAGE ON SCHEMA public TO avanyam_app, avanyam_audit")
    # DROP SCHEMA also drops pg_default_acl entries, so the runtime roles lose
    # the automatic DML grants they had on every table avanyam_migrate creates.
    # This is why a schema rebuild silently breaks the application role.
    c.execute("""ALTER DEFAULT PRIVILEGES FOR ROLE avanyam_migrate IN SCHEMA public
                 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO avanyam_app""")
    c.execute("""ALTER DEFAULT PRIVILEGES FOR ROLE avanyam_migrate IN SCHEMA public
                 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO avanyam_audit""")
    c.execute("""ALTER DEFAULT PRIVILEGES FOR ROLE avanyam_migrate IN SCHEMA public
                 GRANT USAGE, SELECT ON SEQUENCES TO avanyam_app, avanyam_audit""")
PY

echo "==> Applying migrations"
"$PY" manage.py migrate --database migrate

echo "==> Verifying the runtime role can use the new tables"
"$PY" - <<'PY'
import os, sys
sys.path.insert(0, "src")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
import django; django.setup()
from django.db import connections

with connections["default"].cursor() as c:
    c.execute("""SELECT count(*) FROM information_schema.tables
                 WHERE table_schema='public' AND table_type='BASE TABLE'""")
    total = c.fetchone()[0]
    c.execute("""SELECT count(*) FROM information_schema.tables
                 WHERE table_schema='public' AND table_type='BASE TABLE'
                   AND has_table_privilege(current_user, table_name, 'SELECT')
                   AND has_table_privilege(current_user, table_name, 'INSERT')
                   AND has_table_privilege(current_user, table_name, 'UPDATE')
                   AND has_table_privilege(current_user, table_name, 'DELETE')""")
    dml = c.fetchone()[0]
    c.execute("SELECT has_schema_privilege(current_user,'public','CREATE')")
    ddl = c.fetchone()[0]
    print(f"    tables visible to avanyam_app : {dml}/{total}")
    print(f"    schema CREATE (must be False)  : {ddl}")
    if dml != total or ddl:
        raise SystemExit("    FAILED: runtime role privileges are wrong")
PY

echo "==> Re-seeding people (accounts the guard above cleared)"
if [[ -n "${ACCOUNTS_SEED_PASSWORD_TEMPLATE:-}" ]]; then
  "$PY" manage.py seed_people
else
  echo "    ACCOUNTS_SEED_PASSWORD_TEMPLATE is unset; not re-seeding."
  echo "    Set it and run: ./avanyam_terra/.avanyam_terra_venv/bin/python manage.py seed_people"
fi

echo "==> Rebuild complete"
